org: benclarke
app: patreon
service: patreon

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 20

  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    REDIRECT_URI: ${env:REDIRECT_URI}
    SESSION_KEY: ${env:SESSION_KEY}

  httpApi:
    cors:
      allowedOrigins:
        - 'https://pmoqcq122m.execute-api.us-east-1.amazonaws.com'
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
      allowCredentials: false

functions:
  api:
    handler: ./src/lambda.handler
    events:
      - httpApi:
          path: /{any+}
          method: ANY
package:
  individually: true
  patterns: 
    - '!node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/.prisma/client/query_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'