org: benclarke
app: patreon
service: patreon

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 20

  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    REDIRECT_URI: ${env:REDIRECT_URI}
    SESSION_KEY: ${env:SESSION_KEY}
    BUCKET_ARN: ${env:BUCKET_ARN}
    BUCKET_NAME: ${env:BUCKET_NAME}
    FILE_KEY: ${env:FILE_KEY}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:GetObject"
          Resource: ${env:BUCKET_ARN}

  httpApi:
    cors:
      allowedOrigins:
        - ${env:ORIGIN}
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
      allowCredentials: false

functions:
  api:
    handler: ./src/lambda.handler
    events:
      - httpApi:
          path: /{any+}
          method: ANY
